services:
  mcp-servers:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ${HOME}/.config/gcloud/application_default_credentials.json:/root/.config/gcloud/application_default_credentials.json:ro
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/application_default_credentials.json
      - SENTENCE_TRANSFORMERS_HOME=/app/data/sentence_transformers
      - APP_HOST=0.0.0.0
      - APP_PORT=8001
    env_file:
      - .env
